# lightning.pytorch==2.0.8
seed_everything: 42
trainer:
  callbacks:
    # - class_path: lightning.pytorch.callbacks.EarlyStopping
    #   init_args:
    #     patience: 5
    #     monitor: eval/accumulate
    #     min_delta: 0.0001
    #     patience: 35
    #     verbose: false
    #     mode: max
    #     check_finite: true
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: -1
        save_last: true
        # monitor: eval/accumulate
        mode: max
        dirpath: checkpoints/vanilla7b # how to set the right folder?
        filename: "{epoch}-{step}"
        save_on_train_epoch_end: false
        # every_n_train_steps: 1
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  logger:
      class_path: lightning.pytorch.loggers.WandbLogger
      init_args:
        name: run_name_test
        save_dir: wandb_dir/run_name_test
        project: wandb_project_name
  accelerator: gpu
  strategy:
    class_path: lightning.pytorch.strategies.DDPStrategy
    init_args:
      static_graph: True

  devices: 1
  num_nodes: 2
  precision: 16-mixed
  fast_dev_run: false
  max_epochs: 2
  min_epochs: null
  max_steps: 1000
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: 10
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: 100
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 10
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 1
  default_root_dir: null
model:
  class_path: summarization_llm.llama.LlamaModule
  init_args:
    config:
      # optimizer
      weight_decay: 0.0
      adam_beta1: 0.9
      adam_beta2: 0.999
      adam_epsilon: 1e-08
      learning_rate: 0.00001
      # lora
      r: 32
      lora_alpha: 32
      lora_dropout: 0.05
      bias: "none"
      task_type: "CAUSAL_LM"
    path: meta-llama/Llama-2-7b-chat-hf
data:
  # system_message: null
  model_path: meta-llama/Llama-2-7b-chat-hf
  size: null
  batch_size: 1
  seq_length: 1024
  overwrite: false
ckpt_path: null
